export const PROJECT = {
    FC_NAME : "FC_POINT",
    FC_EN_NAME : "分词任务",
    LBTX_NAME : "LBTX_POINT",
    LBTX_EN_NAME: "类别体系",
    YLSC_NAME : "YLSC_POINT",
    YLSC_EN_NAME : "语料生成",
    GZJL_NAME : "GZJL_POINT",
    GZJL_EN_MAME : "规则建立",
    MXXL_NAME: "MXXL_POINT",
    MXXL_EN_NAME: "模型训练",
    YYYS_NAME: "MXYS_POINT",
    YYYS_EN_NAME: "模型运算",
    MXCS_NAME: "MXCS_POINT",
    MXCS_EN_NAME: "模型测试",
    TPGN_NAME: "TPGN_POINT",
    TPGN_EN_NAME: "图谱概念",
    STXX_NAME: "STCJ_POINT",
    STXX_EN_NAME: "实体创建",
    GXWJL_NAME: "GXJL_POINT",
    GXWJL_EN_NAME: "关系建立",
    SH_NAME: "SHXZ_POINT",
    SH_EN_NAME: "审核选择",
    WDHC_NAME: "WDHC_POINT",
    WDHC_EN_NAME: "文档合成",
    SS_NAME: "ZNTS_POINT",
    SS_EN_NAME: "智能推送",
    SXSB_NAME: "SXSB_POINT",
    SXSB_EN_NAME: "属性识别",
    YBGJ_NAME: "YBGJ_POINT",
    YBGJ_EN_NAME: "样本构建",
}
